# Generated by Django 4.2.7 on 2024-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("block", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="index",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
