# Generated by Django 4.2.7 on 2024-03-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("block", "0003_dep_emp_emps"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("key", models.CharField(max_length=256)),
                ("address", models.CharField(max_length=256)),
            ],
        ),
    ]
